---
- name: install packages needed to build Ruby
  apt: "name={{ item }} state=present"
  with_items:
    - zlib1g-dev
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev

- name: fetch Ruby source code
  get_url:
    url: "{{ ruby_source_url }}"
    dest: "~/ruby-{{ ruby_version }}.tar.gz"

- name: untar Ruby source code
  unarchive:
    src: "~/ruby-{{ ruby_version }}.tar.gz"
    dest: "~/"
    copy: no

- name: build Ruby
  command: >
    {{ item }}
    chdir=~/ruby-{{ ruby_version }}
    creates=/usr/local/bin/ruby
  with_items:
    - ./configure --enable-shared
    - make
    - sudo make install

- name: create symlinks for Ruby and its tools
  file:
    src: "/usr/local/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: yes
  with_items:
    - erb
    - gem
    - irb
    - rake
    - rdoc
    - ruby

- name: add .gemrc
  copy: src=gemrc dest=~/.gemrc owner={{ ansible_ssh_user }} mode=0750

- name: install bundler
  gem: name=bundler state=latest
